services:
#  finshark.api:
#    image: finshark.api
#    build:
#      context: .
#      dockerfile: FinShark.API/Dockerfile
  database:
    image: mysql:8.0.34
    platform: linux/amd64
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}:3306
    healthcheck:
      test: [ "CMD-SHELL", "/usr/bin/mysql --user=root --password=\"$DATABASE_ROOT_PASSWORD\" --execute \"SHOW DATABASES;\" | grep \"$DATABASE_NAME\"" ]
      interval: 2s
      timeout: 10s
      retries: 3
      start_period: 30s
      start_interval: 1s

volumes:
  database-data:
